server:
  port: 9000

backing-services:
  case:
    base-uri: http://localhost:5000
  study-server:
    base-uri: http://localhost:5001
  merge-orchestrator-server:
    base-uri: http://localhost:5020
  notification-server:
    base-uri: http://localhost:5009
  merge-notification-server:
    base-uri: http://localhost:5002
  actions-server:
    base-uri: http://localhost:5022
  config-ui-server:
    base-uri: http://localhost:5011
  config-notification-server:
    base-uri: http://localhost:5010
