server:
  port: 9000

backing-services:
  case:
    base-uri: http://localhost:5000
  study-server:
    base-uri: http://localhost:5001
  merge-orchestrator-server:
    base-uri: http://localhost:5020
  notification-server:
    base-uri: http://localhost:5009
  merge-notification-server:
    base-uri: http://localhost:5002
  actions-server:
    base-uri: http://localhost:5022
  config-server:
    base-uri: http://localhost:5025
  config-notification-server:
    base-uri: http://localhost:5024
  directory-server:
    base-uri: http://localhost:5026
  cgmes-boundary-server:
    base-uri: http://localhost:5021
  report-server:
    base-uri: http://localhost:5028

info:
  hostname: ${HOSTNAME}
